/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pages;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Fachry Ghifary
 */
public class Lobby extends javax.swing.JFrame {

    /**
     * Creates new form Lobby
     */
    public Lobby() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLobby = new javax.swing.JPanel();
        lblTitle1 = new javax.swing.JLabel();
        septr = new javax.swing.JSeparator();
        btnPlay = new javax.swing.JButton();
        btnSetting = new javax.swing.JButton();
        btnLangSwitch = new javax.swing.JButton();
        lblTitle2 = new javax.swing.JLabel();
        lblLicense = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Matching Games");
        setBackground(new java.awt.Color(51, 51, 255));
        setName("mainLobbyFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(420, 420));
        getContentPane().setLayout(null);

        pnlLobby.setBackground(new java.awt.Color(171, 205, 239));
        pnlLobby.setPreferredSize(new java.awt.Dimension(420, 400));
        pnlLobby.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLobbyMouseClicked(evt);
            }
        });
        pnlLobby.setLayout(null);

        lblTitle1.setFont(new java.awt.Font("Comic Sans MS", 3, 32)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(18, 52, 86));
        lblTitle1.setText("  Matching");
        lblTitle1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitle1.setMaximumSize(new java.awt.Dimension(255, 255));
        pnlLobby.add(lblTitle1);
        lblTitle1.setBounds(110, 20, 220, 46);

        septr.setBackground(new java.awt.Color(18, 52, 86));
        septr.setForeground(new java.awt.Color(18, 52, 86));
        pnlLobby.add(septr);
        septr.setBounds(15, 116, 374, 21);

        btnPlay.setBackground(new java.awt.Color(18, 52, 86));
        btnPlay.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(171, 205, 239));
        btnPlay.setText("Play");
        btnPlay.setToolTipText("Play the game!!");
        btnPlay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        pnlLobby.add(btnPlay);
        btnPlay.setBounds(110, 140, 188, 48);

        btnSetting.setBackground(new java.awt.Color(18, 52, 86));
        btnSetting.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnSetting.setForeground(new java.awt.Color(171, 205, 239));
        btnSetting.setText("Setting");
        btnSetting.setToolTipText("Still a dummy :))");
        btnSetting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        btnSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingActionPerformed(evt);
            }
        });
        pnlLobby.add(btnSetting);
        btnSetting.setBounds(110, 210, 188, 48);

        btnLangSwitch.setBackground(new java.awt.Color(18, 52, 86));
        btnLangSwitch.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnLangSwitch.setForeground(new java.awt.Color(171, 205, 239));
        btnLangSwitch.setText("Eng");
        btnLangSwitch.setToolTipText("Change preferred language (Eng / Id)");
        btnLangSwitch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204)));
        btnLangSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLangSwitchActionPerformed(evt);
            }
        });
        pnlLobby.add(btnLangSwitch);
        btnLangSwitch.setBounds(110, 280, 188, 48);

        lblTitle2.setFont(new java.awt.Font("Comic Sans MS", 3, 32)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(18, 52, 86));
        lblTitle2.setText(" Game");
        pnlLobby.add(lblTitle2);
        lblTitle2.setBounds(150, 60, 130, 46);

        lblLicense.setBackground(new java.awt.Color(18, 52, 86));
        lblLicense.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblLicense.setForeground(new java.awt.Color(18, 52, 86));
        lblLicense.setText("  This project are under MIT License");
        lblLicense.setToolTipText("");
        lblLicense.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLicense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLicenseMouseClicked(evt);
            }
        });
        pnlLobby.add(lblLicense);
        lblLicense.setBounds(80, 340, 260, 21);

        getContentPane().add(pnlLobby);
        pnlLobby.setBounds(0, 0, 410, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        System.out.println("Play Button Clicked");
        MatchingGame.run(btnLangSwitch.getText().equals("Eng") ? 0 : 1);
        this.dispose();
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        System.out.println("Setting Button Clicked");
        JOptionPane.showMessageDialog(null, "This is just dummy u dummy", "Setting Button Dummy", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSettingActionPerformed

    private void btnLangSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLangSwitchActionPerformed
        if (btnLangSwitch.getText().equals("Eng")){
            System.out.println("Language Button Clicked: switch language from Eng to Id");
            btnLangSwitch.setText("Id");
            btnLangSwitch.setToolTipText("Mengubah bahasa yang diinginkan (Eng / Id)");
            
            btnSetting.setText("Pengaturan");
            
            btnPlay.setText("Main");
            btnPlay.setToolTipText("Mulai bermain!!");
            
            lblTitle1.setText("Mencocokkan");
            lblTitle2.setText("Gambar");
            
            lblLicense.setText("Proyek ini berada di bawah Lisensi MIT");
            
            this.setTitle("Mencocokkan Gambar");
        } else {
            System.out.println("Language Button Clicked: switch language from Id to Eng");
            btnLangSwitch.setText("Eng");
            btnLangSwitch.setToolTipText("Change preferred language (Eng / Id)");
            
            btnSetting.setText("Setting");
            
            btnPlay.setText("Play");
            btnPlay.setToolTipText("Start the game!!");
            
            lblTitle1.setText("  Matching");
            lblTitle2.setText(" Game");
            
            lblLicense.setText("  This project are under MIT License");
            
            this.setTitle("Matching Games");
        }
    }//GEN-LAST:event_btnLangSwitchActionPerformed

    private void lblLicenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLicenseMouseClicked
        // TODO add your handling code here:
        String MITLicenseText = 
            """
            MIT License
            
            Copyright (c) 2024 Fachry Ghifary
            
            Permission is hereby granted, free of charge, to any person obtaining a copy
            of this software and associated documentation files (the "Software"), to deal
            in the Software without restriction, including without limitation the rights
            to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
            copies of the Software, and to permit persons to whom the Software is
            furnished to do so, subject to the following conditions:
            
            The above copyright notice and this permission notice shall be included in all
            copies or substantial portions of the Software.
            
            THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
            IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
            FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
            AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
            LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
            OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
            THE SOFTWARE.""";
        JOptionPane.showMessageDialog(null, MITLicenseText, "MIT License", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lblLicenseMouseClicked
    
    private void drawSwastika(Graphics2D g, MouseEvent evt){
        int[] xPoints = {
            evt.getX()+0,
            evt.getX()-14,
            evt.getX()-14,
            evt.getX()-4,
            evt.getX()-4,
            evt.getX()-14,
            evt.getX()-14,
            evt.getX()-10,
            evt.getX()-10,
            evt.getX()-4,
            evt.getX()-4,
            evt.getX()+10,
            evt.getX()+10,
            evt.getX()+0,
            evt.getX()+0,
            evt.getX()+10,
            evt.getX()+10,
            evt.getX()+6,
            evt.getX()+6,
            evt.getX()+0,
        };
        int[] yPoints = {
            evt.getY()-10,
            evt.getY()-10,
            evt.getY()-6,
            evt.getY()-6,
            evt.getY()+0,
            evt.getY()+0,
            evt.getY()+14,
            evt.getY()+14,
            evt.getY()+4,
            evt.getY()+4,
            evt.getY()+14,
            evt.getY()+14,
            evt.getY()+10,
            evt.getY()+10,
            evt.getY()+4,
            evt.getY()+4,
            evt.getY()-10,
            evt.getY()-10,
            evt.getY()+0,
            evt.getY()+0,
        };
        Color pnlColor = pnlLobby.getBackground();
        int invRed = 255-pnlColor.getRed();
        int invGreen = 255-pnlColor.getGreen();
        int invBlue = 255-pnlColor.getBlue();
        System.out.printf("Draw Swastika RGB Invert: %d %d %d\n", invRed, invGreen, invBlue);
        g.setColor(new Color(invRed, invGreen, invBlue));
        g.fillPolygon(xPoints, yPoints, xPoints.length);
        g.drawPolygon(xPoints, yPoints, xPoints.length);    
        long ms = System.currentTimeMillis();
        while(true){
            long temp = System.currentTimeMillis();
            if (temp - ms >= 200){
                pnlLobby.repaint(evt.getX()-25, evt.getY()-25, evt.getX()+50, evt.getY()+50);
                break;
            }
        }
    }
    
    private void drawAnimalImage(Graphics2D g, MouseEvent evt){
        int r = (int)(Math.random()*36+1);
        Image imgClick = new ImageIcon(System.getProperty("user.dir")+String.format("\\assets\\image\\%d.png", r)).getImage();
        int xrender = evt.getX()-imgClick.getWidth(null)/2;
        int yrender = evt.getY()-imgClick.getHeight(null)/2;
        int widthRepaint = evt.getX()+imgClick.getWidth(null);
        int heightRepaint = evt.getY()+imgClick.getHeight(null);
        g.drawImage(imgClick, xrender, yrender, null);
//        g.drawImage(imgClick, xrender, yrender, 50, 50, null); // jika ingin resize image
        long ms = System.currentTimeMillis();
        while(true){
            long temp = System.currentTimeMillis();
            if (temp - ms >= 200){
                pnlLobby.repaint(xrender, yrender, widthRepaint, heightRepaint);
//                pnlLobby.repaint(evt.getX()-25, evt.getY()-25, evt.getX()+50, evt.getY()+50);
                break;
            }
        }
    }
    
    private void pnlLobbyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLobbyMouseClicked
        System.out.printf("Mouse Clicked to Lobby Panel at (%d, %d)\n", evt.getX(), evt.getY());
        Graphics2D g = (Graphics2D)pnlLobby.getGraphics();
//        drawSwastika(g, evt);
        drawAnimalImage(g, evt);
    }//GEN-LAST:event_pnlLobbyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Motif".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /*
        MAIN COLOR :
        ABCDEF LIGHT BLUE
        0033CC BLUE IDK
        123456 DARK BLUE
        */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            System.out.println(System.getProperty("user.dir"));
            Lobby l = new Lobby();
            l.setResizable(false);
//            l.setIconImage(new ImageIcon("D:\\NETBEANS\\PemVis\\Project\\MatchingGames\\assets\\image\\logoMatchingGames2.png").getImage());
            l.setIconImage(new ImageIcon(System.getProperty("user.dir")+"\\assets\\image\\logoMatchingGames2.png").getImage());
            l.setLocationRelativeTo(null);
            l.pack();
            l.setVisible(true);

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLangSwitch;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnSetting;
    private javax.swing.JLabel lblLicense;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JPanel pnlLobby;
    private javax.swing.JSeparator septr;
    // End of variables declaration//GEN-END:variables
}
